export const camposTaxon = [
    { label: "ID del taxón", name: "taxonID", help: "Identificador único del taxón (por ejemplo: UCO:ESPECIE:12345)." },
    {
        label: "ID del nombre científico",
        name: "scientificNameID",
        help: "Identificador del nombre científico asociado al taxón.",
    },
    {
        label: "Nombre científico",
        name: "scientificName",
        help: "Nombre científico válido del organismo, sin autoría ni abreviaturas.",
    },
    {
        label: "Autoría del nombre científico",
        name: "scientificNameAuthorship",
        help: "Autoría del nombre científico, por ejemplo: (Torr.) J.T. Howell.",
    },
    {
        label: "Clasificación superior",
        name: "higherClassification",
        help: "Clasificación taxonómica superior (p. ej. Reino > Filo > Clase).",
    },
    { label: "Reino", name: "kingdom", help: "Reino taxonómico, por ejemplo: Animalia o Plantae." },
    { label: "Filo", name: "phylum", help: "Filo o división taxonómica." },
    { label: "Clase", name: "class", help: "Clase taxonómica." },
    { label: "Orden", name: "order", help: "Orden taxonómico." },
    { label: "Familia", name: "family", help: "Familia taxonómica." },
    { label: "Subfamilia", name: "subfamily", help: "Subfamilia (si aplica)." },
    { label: "Género", name: "genus", help: "Género del organismo." },
    // { label: "Nombre genérico", name: "genericName" },
    { label: "Subgénero", name: "subgenus", help: "Subgénero (si aplica)." },
    // { label: "Epíteto infragenérico", name: "infragenericEpithet" },
    // { label: "Epíteto específico", name: "specificEpithet" },
    // { label: "Epíteto infragenérico", name: "infraspecificEpithet" },
    { label: "Epíteto específico", name: "cultivarEpithet", help: "Epíteto cultivar, usado en plantas cultivadas." },
    { label: "Rango del taxón", name: "taxonRank", help: "Rango taxonómico del registro (especie, género, familia, etc.)." },
    { label: "Rango del taxón original", name: "verbatimTaxonRank", help: "Rango tal como fue registrado originalmente." },
    { label: "Nombre vernacular", name: "vernacularName", type: "textarea", help: "Nombre común o vernáculo del organismo." },
    // { label: "Estado taxonómico", name: "taxonomicStatus" },
    // { label: "Uso del nombre aceptado", name: "acceptedNameUsage" },
    // { label: "ID del uso del nombre aceptado", name: "acceptedNameUsageID" },
    // { label: "Uso del nombre del padre", name: "parentNameUsage" },
    // { label: "ID del uso del nombre del padre", name: "parentNameUsageID" },
    // { label: "Uso del nombre original", name: "originalNameUsage" },
    // { label: "ID del uso del nombre original", name: "originalNameUsageID" },
    // { label: "Nombre según", name: "nameAccordingTo" },
    // { label: "ID del nombre según", name: "nameAccordingToID" },
    // { label: "Publicado en", name: "namePublishedIn" },
    // { label: "ID de publicación", name: "namePublishedInID" },
    // { label: "Año de publicación", name: "namePublishedInYear" },
    // { label: "ID del concepto del taxón", name: "taxonConceptID" },
    // { label: "Código nomenclatural", name: "nomenclaturalCode" },
    // { label: "Estado nomenclatural", name: "nomenclaturalStatus" },
    // { label: "Comentarios del taxón", name: "taxonRemarks" },
    { label: "ID de la identificación", name: "identificationID" },
    {
        label: "Identificado por",
        name: "identifiedBy",
        help: "Nombre(s) completos de la(s) persona(s) que realizaron la identificación.",
    },
    { label: "ID del identificado por", name: "identifiedByID" },
    { label: "Fecha de identificación", name: "dateIdentified" },
    { label: "Referencia de la identificación", name: "identificationReferences" },
    // { label: "Estado de verificación de la identificación", name: "identificationVerificationStatus" },
    // { label: "Estado del tipo", name: "typeStatus" },
    // { label: "Identificación original", name: "verbatimIdentification" },
    { label: "Comentarios de la identificación", type: "textarea", name: "identificationRemarks" },
    // { label: "Calificador de la identificación", name: "identificationQualifier" },
]

export const camposEvento = [
    { label: "Número de colector", name: "recordNumber", help: "Número asignado por el colector para este registro." },
    { label: "Registrado por", name: "recordedBy", help: "Nombre(s) de la(s) persona(s) que registraron la observación." },
    // { label: "ID del registrado por", name: "recordedByID" },
    // { label: "ID del organismo", name: "organismID" },
    { label: "Número de individuos", name: "individualCount", help: "Cantidad de individuos observados (solo números)." },
    // { label: "Cantidad del organismo", name: "organismQuantity" },
    {
        label: "Tipo de cantidad del organismo",
        name: "organismQuantityType",
        type: "select",
        options: ["Individuos", "gramos", "mililitros", "muestra botánica", "Porcentaje de cobertura", "Células por litro"],
        help: "Unidad o tipo de medida utilizada para cuantificar el organismo.",
    },
    {
        label: "Colección asociada",
        name: "reference_by",
        type: "select",
        help: "Referencia bibliográfica asociada a la identificación o registro.",
    },
    { label: "Nombre del organismo", name: "organismName", help: "Nombre común o descripción del organismo observado." },
    // { label: "Alcance del organismo", name: "organismScope", help: "Alcance o contexto del organismo (ej. adulto, larva)." },
    {
        label: "Organismos asociados",
        name: "associatedOrganisms",
        help: "Otros organismos que están asociados o presentes con el registro.",
    },
    {
        label: "Identificaciones previas",
        name: "previousIdentifications",
        help: "Identificaciones anteriores registradas para este espécimen.",
    },
    {
        label: "Comentarios del organismo",
        name: "organismRemarks",
        type: "textarea",
        help: "Observaciones adicionales sobre el organismo.",
    },
    {
        label: "Sexo",
        name: "sex",
        type: "select",
        options: ["Macho", "Hembra", "Hermafrodita", "Desconocido"],
        help: "Sexo del organismo si se conoce.",
    },
    { label: "Etapa de vida", name: "lifeStage", help: "Etapa ontogénica del organismo (ej. adulto, juvenil)." },
    // { label: "Condición reproductiva", name: "reproductiveCondition" },
    // { label: "Comportamiento", name: "behavior" },
    {
        label: "Medios de establecimiento",
        name: "establishmentMeans",
        type: "select",
        options: [
            "Native",
            "NativeReintroduced",
            "Introduced",
            "IntroducedAssistedColonisation",
            "Vagrant",
            "Uncertain",
            "Endémica",
        ],
        help: "Indica cómo se estableció la especie en la localidad (nativa, introducida, etc.).",
    },
    // { label: "Grado de establecimiento", name: "degreeOfEstablishment" },
    // { label: "Ruta", name: "pathway" },
    // { label: "Estado del registro biológico", name: "occurrenceStatus" },
    {
        label: "Preparaciones",
        name: "preparations",
        help: "Preparaciones realizadas del espécimen (ej. piel, cráneo). Separe con ' | ' si son varias.",
    },
    // { label: "Disposición", name: "disposition" },
    // { label: "Otros números de catálogo", name: "otherCatalogNumbers" },
    // { label: "Medios asociados", name: "associatedMedia" },
    // { label: "Registros asociados", name: "associatedOccurrences" },
    // { label: "Referencias asociadas", name: "associatedReferences" },
    // { label: "Secuencias asociadas", name: "associatedSequences" },
    // { label: "Taxones asociados", name: "associatedTaxa" },
    {
        label: "Comentario del registro biológico",
        name: "occurrenceRemarks",
        help: "Comentarios generales sobre el registro biológico.",
    },
]

export const camposDatos = [
    { label: "ID del registro biológico", name: "occurrenceID", help: "Identificador único del registro biológico (si aplica)." },
    {
        label: "Base del registro",
        name: "basisOfRecord",
        type: "select",
        options: [
            "PreservedSpecimen",
            "LivingSpecimen",
            "HumanObservation",
            "MachineObservation",
            "MaterialSample",
            "FossilSpecimen",
        ],
        help: "Tipo de registro (ej. espécimen preservado, observación humana).",
    },
    {
        label: "Tipo",
        name: "type",
        type: "select",
        options: ["PhysicalObject", "Event", "StillImage", "MovingImage", "Sound"],
        help: "Tipo de recurso asociado al registro (físico o digital).",
    },
    // { label: "Idioma", name: "language" },
    // { label: "Código de la institución", name: "institutionCode" },
    // { label: "ID de la institución", name: "institutionID" },
    // { label: "Código de la colección", name: "collectionCode" },
    // { label: "ID de la colección", name: "collectionID" },
    // { label: "Número de catálogo", name: "catalogNumber" },
    { label: "Nombre del conjunto de datos", name: "datasetName", help: "Nombre del dataset al que pertenece este registro." },
    // { label: "Modificado", name: "modified" },
    // { label: "Licencia", name: "license" },
    // { label: "Titular de los derechos", name: "rightsHolder" },
    // { label: "Derechos de acceso", name: "accessRights" },
    // { label: "Código de la institución propietaria", name: "ownerInstitutionCode" },
    // { label: "Información retenida", name: "informationWithheld" },
    // { label: "Generalizaciones de datos", name: "dataGeneralizations" },
    {
        label: "Propiedades dinámicas",
        name: "dynamicProperties",
        help: "Propiedades en formato JSON que describen atributos adicionales del registro.",
    },
    { label: "Cita bibliográfica", name: "bibliographicCitation" },
    { label: "Referencias", name: "references" },
]

export const camposFamilia = [
    // { label: "Número de campo", name: "fieldNumber" },
    // { label: "Notas de campo", name: "fieldNotes" },

    // { label: "ID de la ubicación", name: "locationID" },
    // {
    //     label: "Continente",
    //     name: "continent",
    //     type: "select",
    //     options: ["América del Sur", "América del Norte", "África", "Asia", "Europa", "Oceanía", "Antártida"],
    // },
    { label: "Cuerpo de agua", name: "waterBody", help: "Nombre del cuerpo de agua si aplica." },
    // { label: "Isla", name: "island" },
    { label: "País", name: "country", help: "País donde se realizó el registro." },
    // { label: "Código del país", name: "countryCode" },
    { label: "Departamento", name: "stateProvince", help: "Departamento o provincia donde se ubicó el registro." },
    { label: "Municipio", name: "county", help: "Municipio o condado donde se ubicó el registro." },
    {
        label: "Centro poblado / Cabecera municipal",
        name: "municipality",
        help: "Nombre del centro poblado o cabecera municipal.",
    },
    { label: "Localidad", name: "locality", help: "Localidad o sitio específico de la observación." },
]

export const camposOtros = [
    // { label: "ID de la ubicación", name: "locationID" },
    // { label: "Geografía superior", name: "higherGeography" },
    // { label: "ID de la geografía superior", name: "higherGeographyID" },
    // { label: "Continente", name: "continent" },
    // { label: "Cuerpo de agua", name: "waterBody" },
    // { label: "Grupo de islas", name: "islandGroup" },
    // { label: "Isla", name: "island" },
    // { label: "País", name: "country" },
    // { label: "Código del país", name: "countryCode" },
    // { label: "Estado/Provincia", name: "stateProvince" },
    // { label: "Condado", name: "county" },
    // { label: "Municipio", name: "municipality" },
    // { label: "Localidad", name: "locality" },
    // { label: "Localidad original", name: "verbatimLocality" },
    {
        label: "Elevación original",
        name: "verbatimElevation",
        type: "number",
        help: "Elevación tal como fue registrada originalmente (si aplica).",
    },
    { label: "Elevación mínima en metros", name: "minimumElevationInMeters", type: "number", help: "Elevación mínima en metros." },
    { label: "Elevación máxima en metros", name: "maximumElevationInMeters", type: "number", help: "Elevación máxima en metros." },
    // { label: "Datum vertical", name: "verticalDatum" },
    { label: "Profundidad original", name: "verbatimDepth", type: "number", help: "Profundidad registrada originalmente (si aplica)." },
    { label: "Profundidad mínima en metros", name: "minimumDepthInMeters", type: "number", help: "Profundidad mínima en metros." },
    { label: "Profundidad máxima en metros", name: "maximumDepthInMeters", type: "number", help: "Profundidad máxima en metros." },
    // { label: "Distancia mínima sobre la superficie en metros", name: "minimumDistanceAboveSurfaceInMeters" },
    // { label: "Distancia máxima sobre la superficie en metros", name: "maximumDistanceAboveSurfaceInMeters" },
    { label: "Ubicación de acuerdo con", name: "locationAccordingTo", help: "Fuente que describe la ubicación." },
    { label: "Comentarios de la ubicación", name: "locationRemarks", help: "Observaciones adicionales sobre la ubicación." },
    { label: "Latitud original", name: "verbatimLatitude", type: "text", help: "Latitud tal como fue registrada originalmente." },
    { label: "Longitud original", name: "verbatimLongitude", type: "text", help: "Longitud tal como fue registrada originalmente." },
    { label: "Coordenadas originales", name: "verbatimCoordinates", help: "Coordenadas en el formato original registrado." },
    // { label: "Sistema original de coordenadas", name: "verbatimCoordinateSystem" },
    // { label: "SRS original", name: "verbatimSRS" },
    { label: "Latitud decimal", name: "decimalLatitude", help: "Latitud en grados decimales (-90 a 90)." },
    { label: "Longitud decimal", name: "decimalLongitude", help: "Longitud en grados decimales (-180 a 180)." },
    // { label: "Datum geodésico", name: "geodeticDatum" },
    // { label: "Incertidumbre de coordenadas en metros", name: "coordinateUncertaintyInMeters" },
    // { label: "Precisión de coordenadas", name: "coordinatePrecision" },
    // { label: "Ajuste espacial del radio del punto", name: "pointRadiusSpatialFit" },
    // { label: "Huella WKT", name: "footprintWKT" },
    // { label: "SRS de la huella", name: "footprintSRS" },
    // { label: "Ajuste espacial de la huella", name: "footprintSpatialFit" },
    { label: "Georreferenciado por", name: "georeferencedBy", help: "Persona(s) que realizaron la georreferenciación." },
    // { label: "Fecha de georreferenciación", name: "georeferencedDate" },
    // { label: "Protocolo de georreferenciación", name: "georeferenceProtocol" },
    // { label: "Fuentes de georreferenciación", name: "georeferenceSources" },
    // { label: "Estado de verificación de georreferenciación", name: "georeferenceVerificationStatus" },
    // { label: "Comentarios de georreferenciación", name: "georeferenceRemarks" },
]

export const camposRegsitre = [
    //     { label: "ID del contexto geológico", name: "geologicalContextID" },
    //     { label: "Eón más antiguo o eonotema más bajo", name: "earliestEonOrLowestEonothem" },
    //     { label: "Eón más reciente o eonotema más alto", name: "latestEonOrHighestEonothem" },
    //     { label: "Era más antigua o eratema más bajo", name: "earliestEraOrLowestErathem" },
    //     { label: "Era más reciente o eratema más alto", name: "latestEraOrHighestErathem" },
    //     { label: "Período más antiguo o sistema más bajo", name: "earliestPeriodOrLowestSystem" },
    //     { label: "Período más reciente o sistema más alto", name: "latestPeriodOrHighestSystem" },
    //     { label: "Época más antigua o serie más baja", name: "earliestEpochOrLowestSeries" },
    //     { label: "Época más reciente o serie más alta", name: "latestEpochOrHighestSeries" },
    //     { label: "Edad más antigua o etapa más baja", name: "earliestAgeOrLowestStage" },
    //     { label: "Edad más reciente o etapa más alta", name: "latestAgeOrHighestStage" },
    //     { label: "Zona bioestratigráfica más baja", name: "lowestBiostratigraphicZone" },
    //     { label: "Zona bioestratigráfica más alta", name: "highestBiostratigraphicZone" },
    //     { label: "Términos litoestratigráficos", name: "lithostratigraphicTerms" },
    //     { label: "Grupo", name: "group" },
    //     { label: "Formación", name: "formation" },
    //     { label: "Miembro", name: "member" },
    //     { label: "Capa", name: "bed" },
    // { label: "ID del evento", name: "eventID" },
    // { label: "ID del evento padre", name: "parentEventID" },
    { label: "Protocolo de muestreo", name: "samplingProtocol", help: "Protocolo o método utilizado para la recolección." },
    // { label: "Valor del tamaño de la muestra", name: "sampleSizeValue" },
    // { label: "Unidad del tamaño de la muestra", name: "sampleSizeUnit" },
    { label: "Esfuerzo de muestreo", name: "samplingEffort", help: "Esfuerzo invertido en el muestreo (ej. horas, transectos)." },
    { label: "Fecha del evento", name: "eventDate", help: "Fecha del evento (formato ISO preferido: AAAA-MM-DD)." },
    { label: "Comentarios del evento", name: "eventRemarks", type: "textarea", help: "Observaciones generales sobre el evento." },
    // { label: "Día inicial del año", name: "startDayOfYear" },
    // { label: "Día final del año", name: "endDayOfYear" },
    // { label: "Año", name: "year" },
    // { label: "Mes", name: "month" },
    // { label: "Día", name: "day" },
    // { label: "Fecha original del evento", name: "verbatimEventDate" },
    { label: "Hora del evento", name: "eventTime", help: "Hora del evento (HH:mm o HH:mm:ss)." },
    { label: "Hábitat", name: "habitat", help: "Descripción del hábitat donde se realizó el registro." },
    // { label: "ID de la muestra material", name: "materialSampleID" },
]
