export  const camposTaxon  = [
  { label: "ID del taxón", name: "taxonID" },
  { label: "ID del nombre científico", name: "scientificNameID" },
  { label: "Nombre científico", name: "scientificName" },
  { label: "Autoría del nombre científico", name: "scientificNameAuthorship" },
  { label: "Clasificación superior", name: "higherClassification" },
  { label: "Reino", name: "kingdom" },
  { label: "Filo", name: "phylum" },
  { label: "Clase", name: "class" },
  { label: "Orden", name: "order" },
  { label: "Familia", name: "family" },
  { label: "Subfamilia", name: "subfamily" },
  { label: "Género", name: "genus" },
  { label: "Nombre genérico", name: "genericName" },
  { label: "Subgénero", name: "subgenus" },
  { label: "Epíteto infragenérico", name: "infragenericEpithet" },
  { label: "Epíteto específico", name: "specificEpithet" },
  { label: "Epíteto infragenérico", name: "infraspecificEpithet" },
  { label: "Epíteto cultivar", name: "cultivarEpithet" },
  { label: "Rango del taxón", name: "taxonRank" },
  { label: "Rango del taxón original", name: "verbatimTaxonRank" },
  { label: "Nombre vernáculo", name: "vernacularName" },
  { label: "Estado taxonómico", name: "taxonomicStatus" },
  { label: "Uso del nombre aceptado", name: "acceptedNameUsage" },
  { label: "ID del uso del nombre aceptado", name: "acceptedNameUsageID" },
  { label: "Uso del nombre del padre", name: "parentNameUsage" },
  { label: "ID del uso del nombre del padre", name: "parentNameUsageID" },
  { label: "Uso del nombre original", name: "originalNameUsage" },
  { label: "ID del uso del nombre original", name: "originalNameUsageID" },
  { label: "Nombre según", name: "nameAccordingTo" },
  { label: "ID del nombre según", name: "nameAccordingToID" },
  { label: "Publicado en", name: "namePublishedIn" },
  { label: "ID de publicación", name: "namePublishedInID" },
  { label: "Año de publicación", name: "namePublishedInYear" },
  { label: "ID del concepto del taxón", name: "taxonConceptID" },
  { label: "Código nomenclatural", name: "nomenclaturalCode" },
  { label: "Estado nomenclatural", name: "nomenclaturalStatus" },
  { label: "Comentarios del taxón", name: "taxonRemarks" },
  ];
    
export const camposEvento = [
    { label: "Número de registro", name: "recordNumber" },
    { label: "Registrado por", name: "recordedBy" },
    { label: "ID del registrado por", name: "recordedByID" },
    { label: "ID del organismo", name: "organismID" },
    { label: "Número de individuos", name: "individualCount" },
    { label: "Cantidad del organismo", name: "organismQuantity" },
    { label: "Tipo de cantidad del organismo", name: "organismQuantityType" },
    { label: "Nombre del organismo", name: "organismName" },
    { label: "Alcance del organismo", name: "organismScope" },
    { label: "Organismos asociados", name: "associatedOrganisms" },
    { label: "Identificaciones previas", name: "previousIdentifications" },
    { label: "Comentarios del organismo", name: "organismRemarks" },
    { label: "Sexo", name: "sex" },
    { label: "Etapa de vida", name: "lifeStage" },
    { label: "Condición reproductiva", name: "reproductiveCondition" },
    { label: "Comportamiento", name: "behavior" },
    { label: "Medios de establecimiento", name: "establishmentMeans" },
    { label: "Grado de establecimiento", name: "degreeOfEstablishment" },
    { label: "Ruta", name: "pathway" },
    { label: "Estado del registro biológico", name: "occurrenceStatus" },
    { label: "Preparaciones", name: "preparations" },
    { label: "Disposición", name: "disposition" },
    { label: "Otros números de catálogo", name: "otherCatalogNumbers" },
    { label: "Medios asociados", name: "associatedMedia" },
    { label: "Registros asociados", name: "associatedOccurrences" },
    { label: "Referencias asociadas", name: "associatedReferences" },
    { label: "Secuencias asociadas", name: "associatedSequences" },
    { label: "Taxones asociados", name: "associatedTaxa" },
    { label: "Comentarios del registro biológico", name: "occurrenceRemarks" },
    { label: "ID de la muestra material", name: "materialSampleID" },
  ];

   export  const camposDatos = [
    { label: "ID del registro biológico", name: "occurrenceID" },
    {
      label: "Base del registro",
      name: "basisOfRecord",
      type: "select",
      options: [
        "PreservedSpecimen",
        "LivingSpecimen",
        "HumanObservation",
        "MachineObservation",
        "MaterialSample",
        "FossilSpecimen",
      ],
    },
    {
      label: "Tipo",
      name: "type",
      type: "select",
      options: [
        "PhysicalObject",
        "Event",
        "StillImage",
        "MovingImage",
        "Sound",
      ],
    },
    { label: "Idioma", name: "language" },
    { label: "Código de la institución", name: "institutionCode" },
    { label: "ID de la institución", name: "institutionID" },
    { label: "Código de la colección", name: "collectionCode" },
    { label: "ID de la colección", name: "collectionID" },
    { label: "Número de catálogo", name: "catalogNumber" },
    { label: "Nombre del conjunto de datos", name: "datasetName" },
    { label: "Modificado", name: "modified" },
    { label: "Licencia", name: "license" },
    { label: "Titular de los derechos", name: "rightsHolder" },
    { label: "Derechos de acceso", name: "accessRights" },
    { label: "Código de la institución propietaria", name: "ownerInstitutionCode" },
    { label: "Información retenida", name: "informationWithheld" },
    { label: "Generalizaciones de datos", name: "dataGeneralizations" },
    { label: "Propiedades dinámicas", name: "dynamicProperties" },
    { label: "Cita bibliográfica", name: "bibliographicCitation" },
    { label: "Referencias", name: "references" },
  ];

   export const camposFamilia = [
  { label: "ID del evento", name: "eventID" },
  { label: "ID del evento padre", name: "parentEventID" },
  { label: "Protocolo de muestreo", name: "samplingProtocol" },
  { label: "Valor del tamaño de la muestra", name: "sampleSizeValue" },
  { label: "Unidad del tamaño de la muestra", name: "sampleSizeUnit" },
  { label: "Esfuerzo de muestreo", name: "samplingEffort" },
  { label: "Fecha del evento", name: "eventDate" },
  { label: "Día inicial del año", name: "startDayOfYear" },
  { label: "Día final del año", name: "endDayOfYear" },
  { label: "Año", name: "year" },
  { label: "Mes", name: "month" },
  { label: "Día", name: "day" },
  { label: "Fecha original del evento", name: "verbatimEventDate" },
  { label: "Hora del evento", name: "eventTime" },
  { label: "Hábitat", name: "habitat" },
  { label: "Número de campo", name: "fieldNumber" },
  { label: "Notas de campo", name: "fieldNotes" },
  { label: "Comentarios del evento", name: "eventRemarks" },
  { label: "ID de la ubicación", name: "locationID" },
  {
    label: "Continente",
    name: "continent",
    type: "select",
    options: [
      "América del Sur",
      "América del Norte",
      "África",
      "Asia",
      "Europa",
      "Oceanía",
      "Antártida",
    ],
  },
  { label: "Cuerpo de agua", name: "waterBody" },
  { label: "Isla", name: "island" },
  { label: "País", name: "country" },
  { label: "Código del país", name: "countryCode" },
  { label: "Departamento", name: "stateProvince" },
  { label: "Municipio", name: "county" },
  { label: "Centro poblado / Cabecera municipal", name: "municipality" },
  { label: "Localidad", name: "locality" },
]; 

export  const camposOtros = [
  { label: "ID de la ubicación", name: "locationID" },
  { label: "Geografía superior", name: "higherGeography" },
  { label: "ID de la geografía superior", name: "higherGeographyID" },
  { label: "Continente", name: "continent" },
  { label: "Cuerpo de agua", name: "waterBody" },
  { label: "Grupo de islas", name: "islandGroup" },
  { label: "Isla", name: "island" },
  { label: "País", name: "country" },
  { label: "Código del país", name: "countryCode" },
  { label: "Estado/Provincia", name: "stateProvince" },
  { label: "Condado", name: "county" },
  { label: "Municipio", name: "municipality" },
  { label: "Localidad", name: "locality" },
  { label: "Localidad original", name: "verbatimLocality" },
  { label: "Elevación original", name: "verbatimElevation" },
  { label: "Elevación mínima en metros", name: "minimumElevationInMeters" },
  { label: "Elevación máxima en metros", name: "maximumElevationInMeters" },
  { label: "Datum vertical", name: "verticalDatum" },
  { label: "Profundidad original", name: "verbatimDepth" },
  { label: "Profundidad mínima en metros", name: "minimumDepthInMeters" },
  { label: "Profundidad máxima en metros", name: "maximumDepthInMeters" },
  { label: "Distancia mínima sobre la superficie en metros", name: "minimumDistanceAboveSurfaceInMeters" },
  { label: "Distancia máxima sobre la superficie en metros", name: "maximumDistanceAboveSurfaceInMeters" },
  { label: "Ubicación de acuerdo con", name: "locationAccordingTo" },
  { label: "Comentarios de la ubicación", name: "locationRemarks" },
  { label: "Latitud original", name: "verbatimLatitude" },
  { label: "Longitud original", name: "verbatimLongitude" },
  { label: "Coordenadas originales", name: "verbatimCoordinates" },
  { label: "Sistema original de coordenadas", name: "verbatimCoordinateSystem" },
  { label: "SRS original", name: "verbatimSRS" },
  { label: "Latitud decimal", name: "decimalLatitude" },
  { label: "Longitud decimal", name: "decimalLongitude" },
  { label: "Datum geodésico", name: "geodeticDatum" },
  { label: "Incertidumbre de coordenadas en metros", name: "coordinateUncertaintyInMeters" },
  { label: "Precisión de coordenadas", name: "coordinatePrecision" },
  { label: "Ajuste espacial del radio del punto", name: "pointRadiusSpatialFit" },
  { label: "Huella WKT", name: "footprintWKT" },
  { label: "SRS de la huella", name: "footprintSRS" },
  { label: "Ajuste espacial de la huella", name: "footprintSpatialFit" },
  { label: "Georreferenciado por", name: "georeferencedBy" },
  { label: "Fecha de georreferenciación", name: "georeferencedDate" },
  { label: "Protocolo de georreferenciación", name: "georeferenceProtocol" },
  { label: "Fuentes de georreferenciación", name: "georeferenceSources" },
  { label: "Estado de verificación de georreferenciación", name: "georeferenceVerificationStatus" },
  { label: "Comentarios de georreferenciación", name: "georeferenceRemarks" },
]

  export const camposRegsitre = [
  { label: "ID del contexto geológico", name: "geologicalContextID" },
  { label: "Eón más antiguo o eonotema más bajo", name: "earliestEonOrLowestEonothem" },
  { label: "Eón más reciente o eonotema más alto", name: "latestEonOrHighestEonothem" },
  { label: "Era más antigua o eratema más bajo", name: "earliestEraOrLowestErathem" },
  { label: "Era más reciente o eratema más alto", name: "latestEraOrHighestErathem" },
  { label: "Período más antiguo o sistema más bajo", name: "earliestPeriodOrLowestSystem" },
  { label: "Período más reciente o sistema más alto", name: "latestPeriodOrHighestSystem" },
  { label: "Época más antigua o serie más baja", name: "earliestEpochOrLowestSeries" },
  { label: "Época más reciente o serie más alta", name: "latestEpochOrHighestSeries" },
  { label: "Edad más antigua o etapa más baja", name: "earliestAgeOrLowestStage" },
  { label: "Edad más reciente o etapa más alta", name: "latestAgeOrHighestStage" },
  { label: "Zona bioestratigráfica más baja", name: "lowestBiostratigraphicZone" },
  { label: "Zona bioestratigráfica más alta", name: "highestBiostratigraphicZone" },
  { label: "Términos litoestratigráficos", name: "lithostratigraphicTerms" },
  { label: "Grupo", name: "group" },
  { label: "Formación", name: "formation" },
  { label: "Miembro", name: "member" },
  { label: "Capa", name: "bed" },
]; 

   export  const camposTaxonRank = [
      { label: "ID de la identificación", name: "identificationID" },
      { label: "Identificado por", name: "identifiedBy" },
      { label: "ID del identificado por", name: "identifiedByID" },
      { label: "Fecha de identificación", name: "dateIdentified" },
      { label: "Referencias de la identificación", name: "identificationReferences" },
      { label: "Estado de verificación de la identificación", name: "identificationVerificationStatus" },
      { label: "Estado del tipo", name: "typeStatus" },
      { label: "Identificación original", name: "verbatimIdentification" },
      { label: "Comentarios de la identificación", name: "identificationRemarks" },
      { label: "Calificador de la identificación", name: "identificationQualifier" },
    ];